In [1]:
%load_ext autoreload
%autoreload 2

In [15]:
import numpy as np
from number_finder import *
np.random.seed(10)

In [16]:
test_array=np.random.randint(0, 1000, size=100)

In [17]:
prime_finder(test_array)

array([733, 881,  73, 239, 691,  13, 409, 653,  89, 283, 919,  71,  71,
       461])

In [18]:
fibonacci_finder(np.random.randint(-100, 100, size=100))

array([ 1,  3,  8, 55])

In [19]:
tribonacci_finder(np.random.randint(-100, 100, size=100))

array([-55, -21,   3,   8,  34,  55,  89])